# Generated by Django 6.0 on 2026-02-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0002_come_food_count_pay'),
        ('chef_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Come',
        ),
        migrations.AddField(
            model_name='buyorder',
            name='status',
            field=models.CharField(default='ns', max_length=10),
        ),
        migrations.AlterField(
            model_name='buyorder',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_main.ingredient'),
        ),
        migrations.DeleteModel(
            name='Pay',
        ),
    ]
