# Generated by Django 6.0 on 2026-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0003_delete_come_buyorder_status_alter_buyorder_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='summ',
            field=models.IntegerField(default=1000),
        ),
    ]
