# Generated by Django 6.0 on 2026-02-05 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0004_alter_buyorder_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorder',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
