# Generated by Django 6.0 on 2026-02-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_main', '0006_rename_date_notification_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='payload',
        ),
    ]
