# Generated by Django 6.0 on 2025-12-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('grade', 'last_name'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('cook', 'Повар'), ('admin_main', 'Администратор')], default='student', max_length=255, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(default='', max_length=3, verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='not_like',
            field=models.CharField(default='', max_length=255, verbose_name='not like'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='phone number'),
        ),
    ]
