# Generated by Django 6.0 on 2026-01-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_balance_to_cents(apps, schema_editor):
    User = apps.get_model('users', 'User')
    # До этой миграции balance считался рублями целым числом.
    for u in User.objects.all().only('id', 'balance'):
        bal = getattr(u, 'balance', 0) or 0
        try:
            u.balance_cents = int(bal) * 100
        except Exception:
            u.balance_cents = 0
        u.save(update_fields=['balance_cents'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_cents',
            field=models.IntegerField(default=0, verbose_name='balance (cents)'),
        ),
        migrations.RunPython(copy_balance_to_cents, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.CreateModel(
            name='BalanceTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(verbose_name='amount (cents)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_balance_topups', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пополнение баланса',
                'verbose_name_plural': 'Пополнения баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
