# Generated by Django 6.0 on 2026-01-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_menuitem_allergens_remove_menuitem_max_des_and_more'),
        ('users', '0008_remove_user_balance_user_balance_cents_balancetopup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='menu.allergen'),
        ),
    ]
