# Generated by Django 6.0 on 2026-02-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_main', '0002_alter_ingredient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='remains',
            field=models.IntegerField(default=100),
        ),
    ]
