# Generated by Django 6.0 on 2026-02-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_main', '0003_ingredient_remains'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
    ]
