# Generated by Django 6.0 on 2025-12-25 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('order', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('min_des', models.JSONField(blank=True, default=list)),
                ('max_des', models.JSONField(blank=True, default=list)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('proteins', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbs', models.IntegerField()),
            ],
        ),
    ]
