# Generated by Django 6.0 on 2026-01-16 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('category', models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед')], default='breakfast', max_length=10)),
                ('text', models.TextField()),
                ('stars_count', models.IntegerField(default=3)),
            ],
        ),
    ]
