# Generated by Django 6.0 on 2026-01-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default=234234234, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='day',
            field=models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед')], default='breakfast', max_length=10),
        ),
    ]
