# Generated by Django 6.0 on 2026-01-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_allergen_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='menu.meal'),
        ),
    ]
