# Generated by Django 6.0 on 2026-01-23 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_meals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='max_des',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='min_des',
        ),
    ]
