# Generated by Django 6.0 on 2026-02-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_main', '0001_initial'),
        ('menu', '0007_remove_menuitem_allergens_remove_menuitem_max_des_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass', models.PositiveIntegerField(help_text='Масса в граммах')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chef_main.ingredient')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.meal')),
            ],
            options={
                'verbose_name': 'Ингредиент блюда',
                'verbose_name_plural': 'Ингредиенты блюда',
                'unique_together': {('meal', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='meals', through='menu.MealIngredient', to='chef_main.ingredient'),
        ),
    ]
