# Generated by Django 6.0 on 2026-02-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_mealingredient_meal_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='count_by_days',
            field=models.JSONField(default=dict),
        ),
    ]
