# Generated by Django 6.0 on 2026-02-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='count_by_days',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
