# Generated by Django 6.0 on 2026-02-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_review_day_cleanup'),
        ('menu', '0016_review_day_default_cleanup'),
    ]

    operations = [
    ]
