# Generated by Django 6.0 on 2026-02-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_review_day_default_cleanup'),
        ('menu', '0017_order_status_unique'),
    ]

    operations = [
    ]
