# Generated by Django 6.0 on 2026-02-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_merge_20260206_1329'),
        ('menu', '0018_merge_20260206_1650'),
    ]

    operations = [
    ]
