# Generated by Django 6.0 on 2026-02-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_merge_20260206_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='count_by_days',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
