# Generated by Django 6.0 on 2026-02-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_meal_count_by_days_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='low_rating_notified',
            field=models.BooleanField(default=False),
        ),
    ]
